import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ApolloWrapper } from "@/lib/apollo/ApolloClient";
import { NextAuthProvider, authOptions } from "@/lib/next-auth";
import { getServerSession } from "next-auth";
import { RenderLayout } from "@/layouts/renderLayout";
import dynamic from "next/dynamic";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);
  const AntConfigProvider = dynamic(
    () => import("@/lib/antd/index").then((mod) => mod.default),
    { ssr: false }
  );
  return (
    <html lang="en">
      <body className={inter.className}>
        <ApolloWrapper>
          <NextAuthProvider session={session}>
            <AntConfigProvider>
              <RenderLayout>{children}</RenderLayout>
            </AntConfigProvider>
          </NextAuthProvider>
        </ApolloWrapper>
      </body>
    </html>
  );
}
