import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./../styles/styles.scss";
import { ApolloWrapper } from "@/lib/apollo/ApolloClient";
import { NextAuthProvider, authOptions } from "@/lib/next-auth";
import { getServerSession } from "next-auth";
import { RenderLayout } from "@/layouts/renderLayout";
import dynamic from "next/dynamic";
import AlertModalProvider from "@/context/AlertModalProvider";

const inter = Inter({ subsets: ["latin"] });

const DynamicStyledComponentsProvider = dynamic(
  () => import("@/lib/styledComponents").then((mod) => mod.default),
  { ssr: false }
);
const AntConfigProvider = dynamic(
  () => import("@/lib/antd/index").then((mod) => mod.default),
  { ssr: false }
);
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body className={inter.className}>
        <ApolloWrapper>
          <NextAuthProvider session={session}>
            <AntConfigProvider>
              <DynamicStyledComponentsProvider>
                <AlertModalProvider>
                  <RenderLayout>{children}</RenderLayout>
                </AlertModalProvider>
              </DynamicStyledComponentsProvider>
            </AntConfigProvider>
          </NextAuthProvider>
        </ApolloWrapper>
      </body>
    </html>
  );
}
